### ISSUE TITLE
Content Negotiation by CRS 

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#153]
See https://github.com/opengeospatial/conneg-by-crs. 

This is a new activity that originated from the OGC/W3C SDWIG to draft an RFC for Content Negotiation by CRS for IETF. This is related to the ongoing work in the [W3C Data Exchange Working Group (DXWG)](https://www.w3.org/2017/dxwg/wiki/Main_Page) on content negotiation by profiles.

The work is relevant for the CRS extension. I think we want to continue to allow/support explicit parameters so that we can have "clickable" links and so on (like in the case of formats / media types), but at least we should monitor this and see whether this gets traction.

**Comment by thijsbrentjens** [comment]
Some considerations from experiments conducted in the Netherlands (https://geonovum.github.io/wfs3-experiments/#specification-crs-support):

1. If explicit parameters for "clickable" links are expected for CRSes (instead of / in addition to content negotiation) and an API implementation supports many CRSes and several media types, then the list of alternate links might become very large. Should every combination of CRS and media type have a separate alternate link? Content negotiation would avoid this.
1. (temporary) downside of content negotiation: if content negotiation is required, existing clients probably need to be adapted a bit more.

**Comment by cportele** [comment]
Is there sufficient interest already from client developers in such supporting this as part of content negotiation, too, or maybe mention it in an informative part and wait how the uptake develops.

**Comment by thijsbrentjens** [comment]
I think that's an issue at this moment: I can imagine many client developers aren't aware of this. So that would argue against content negotiation as the only mechanism. It could be an informative part. But for interoperability, it may be better to choose one mechanism

**Comment by cportele** [comment]
Discussed in 2019-10-28 call: We need more input on the questions raised above before making a decision if or how this should be supported. Wait for implementations to appear, make use of it and where we can learn what should be included in OGC API at a later stage. 

Also note that content negotiation (via headers) is orthogonal to the "link explosion" problem.

**Comment by lvdbrink** [comment]
@thijsbrentjens can you point to (Dutch) APIs implementing the use of HTTP headers instead of CRS parameters?

This practice is [described in the Dutch govt API strategy](https://docs.geostandaarden.nl/api/vv-hr-API-Strategie-ext-20190715/#api-40), although it's in the informative part.

**Comment by jabhay** [comment]
Whilst I understand there being some discussion of the benefits of content negotiation as a method of discovery and communication of crs, the existing draft paves the way for this mechanism using a header that is not currently in use as I understand it. The draft of conneg-by-crs names the headers based on what is already in use in Netherlands, and thus there are already implementations of spatial data on the web using the header names discussed in the conneg-by-crs document. These same headers are currently being implemented, and considered for implementation, in APIs in Australia. Perhaps a first step toward lining these two things up, notwithstanding implementation feedback, is to change the names of the headers to at least match so that implementers aren’t doing two different things. We can then use those headers as the single source of feedback.

**Comment by lvdbrink** [comment]
I agree. So, replace `OGC-CRS` with `Content-CRS`.

**Comment by cportele** [comment]
Yes, makes sense to me, too, to reference and use `Content-Crs`. 

The draft of the CRS extension is basically from spring 2018 and pre-dates the [conneg-by-crs work](https://github.com/opengeospatial/conneg-by-crs/blob/master/18-072-Content-Negotiation-by-CRS.md).

One question @jabhay: There does not seem to be any progress and it is unclear if/when there would be a spec with `Content-Crs` that could be referenced? What the timeline for the RFC?

**Comment by jabhay** [comment]
The purpose of drafting this as an RFC to IETF was in case we decided to follow that route, and to give the document some form of structure building on the work done on content negotiation by profile. Initially, it was a paper for OGC members to contribute their thoughts and feedback - and to help give the W3C working groups something to reference. We can simply recommend this to the TC to accept as a discussion paper or such. Would that provide the reference you're after @cportele?

**Comment by cportele** [comment]
Discussion paper is nothing we can normative reference, I think it would have to be something stronger. Since it is mainly HTTP headers that we want to register at IANA, too, an IETF RFC would seem appropriate to me.

Since the header definition and syntax we could also copy the definition for now and hope that it won't change in the conneg-by-crs standard before its approval (in whatever organisation).

**Comment by pvretano** [comment]
@cportele even if there is no "official" reference (would be nice tough) I think I prefer the name Content-Crs to OGC-CRS regardless. Can we not just change it and then, should a reference materialize, we can add that in later?

**Comment by cportele** [comment]
@pvretano - Yes, that was my proposal ("copy the definition for now ").

**Comment by cportele** [comment]
Meeting 2020-05-11: See #364 and the last comments above. @cportele to write a PR.
