### ISSUE TITLE
Subrecommendation 9.B redundant?

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#271]
It is possible that subrecommendation 9.B is redundant because of the presence of requirement 13.B?

![image](https://user-images.githubusercontent.com/11427611/66394067-5cc0f980-e9d4-11e9-91fb-437e7384baa8.png)

**Comment by cportele** [comment]
rec 9.B is not redundant. `type` has to be included in the self/alternate links and should be included in describedBy links. This is why req 13.B and rec. 9.B are part of req 13 and rec. 9 respectively - and requirements/recommendations on their own.

Originally each normative statement was just one block of text, but this was changed when the ATS was added so that there can be references to the pieces of a normative statement. Still, each part of a normative statement has to be understood in the context of the scope of that statement, which is self/alternate links in req 13 and describedBy links in rec 9.

**Comment by heidivanparys** [comment]
Ok, I see, thanks.
