### ISSUE TITLE
PATCH and PUT in simple transactions

### ISSUE THREAD

**Issue by elpaso** [opengeospatial/ogcapi-features#291]
I have some questions/doubts about the simple transactions PUT and PATCH (assuming GeoJSON):

1. PUT: is that correct that this is the only way to replace the geometry of a feature? Looks like it cannot be done with PATCH
2. PUT: is it a partial GeoJSON allowed? Use case: I need to replace the geometry **and** a subset of properties, do I need to PUT the whole "record" here? I see a potential ambiguity if not, especially for handling of null values: what should we do in this case for missing properties? Set them to `null` or leave them unchanged? (I would say the latter)
3. PATCH: is it possible to change only the geometry (same question as 1.)?

**Comment by cportele** [comment]
2020-08-16:

1. PATCH is intended to support replace the geometry, just submit a JSON document just with a "geometry" member with the new geometry. 
2. PUT requires the complete feature, PATCH is for partial updates, e.g., the geometry and some of the properties. the JSON Merge Patch has details about the treatment of `null`. 
3. Yes.

@pvretano will review the current text to see what more we should say to clarify the semantics. We will also add examples.

**Comment by pvretano** [comment]
@elpaso 

1. You can replace the geometry of a feature using PUT but it would involve creating a local copy of the current feature, replacing the geometry with the new geometry in your local copy and then using this modified local copy as the body of a PUT to the feature endpoint.  PATCH, on the other hand, lets you send a request body that contains "instructions" on how to change just the current geometry with a new geometry.  The "instructions" must be encoded as per http://tools.ietf.org/rfc/rfc7396.txt.
2. No.  The body of a PUT must contains a complete feature since PUT replaces the existing feature with the one you specify in the body.  Again to replace the geometry and subset of feature properties you can either create a local copy of the feature, update the geometry and subset of properties in that local copy and then use that local copy as the body of a PUT to the feature endpoint *** OR *** you can encode instructions describing the changes you want to make as per http://tools.ietf.org/rfc/rfc7396.txt and then include those instructions as the body of a PATCH to the feature endpoint.
3. Yes.  PATCH is specifically defined for changing parts of an existing resource without having to transmit an completely new copy of the resource.

So just to summarise:  You change a feature using either PUT or PATCH.  If you use PUT then the body of your request needs to contain a complete, valid feature.  If you use PATCH then the body of your request needs to contains "instructions" as per RFC 7396 that describe the changes you want to make to the existing feature.

**Comment by cportele** [comment]
Meeting 2021-02-15: The questions have been answered as per the specification. @elpaso - if anything is still unclear or not how it should be, please reopen the issue.
