### ISSUE TITLE
Does the CRS extension work for other OGC API resources?

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#295]
The draft of part 2 

* extends the `/collections` and `/collections/{collectionId}` resources
* defines a query parameter `crs` on resources returning data with geometries (`/collections/{collectionId}/items` and `/collections/{collectionId}/items/{featureId}`)
* defines a query parameter `bbox-crs` in addition to the query parameter `bbox`

Consistent with the general approach with parts of OGC API Features before we have OGC API Common, it would be good to get implementation feedback from drafts of other OGC API standards.

Note that the extension does not attempt to cover all cases. Out-of-scope of this part are coordinate reference systems for which no URI exists, i.e., those that are only defined by WKT snippets or by a combination of multiple CRSs. Those aspects would be covered in additional parts, if needed.

**Comment by jerstlouis** [comment]
A CRS is a perfect example of a building block that should work across different types of data and OGC API standards. Like with OGC API - Features being standardized before OGC API - Common and restricting the possibility of achieching an integrated, unified set of OGC API specifications  (e.g. the Collections discussion in Common), I am deeply concerned about CRS getting standardized as part of Features rather than Common or its own stand-alone specification, which would really get the full of attention of everyone. This issue has been raised by OGC API - Coverage as well.

Generally speaking, the current proposal for CRS seems that it would work for everything, but it should probably:
- Stand on its own without explicitly referencing anything from Features, e.g. items or collections (unless these become part of Common), like the approach being considered in OGC API - Tiles right now 
- Leave the possibility for extensions to implement things like WKT snippets, rather than separate parts

**Comment by pvretano** [comment]
@jerstlouis That is the intent but since common is still a ways off and Features needs it now we can define it here and then move it common at the appropriate time.

**Comment by jerstlouis** [comment]
@pvretano I understand that's the intent, but my disagreement is with this fundamantal idea of defining generic things in Features rather than Common. If Features need it, why not propose it to Common or CRS SWG and standardize it there, therefore ensuring it is Features-agnostic?.

We can see from defining Collections in Features and trying to move them to Common (after the fact that it is already standardized, and therefore cannot be changed!) that this approach is not working and actually contributes to delaying the overall OGC API roadmap towards an integrated set of modular specifications, if not straight out hindering it.

**Comment by cportele** [comment]
At least part of it must be in an OGC API Features standard since we need to have normative text that binds, for example, the `crs` parameter to the Features resource. I.e., it is not possible to specify everything independent of the resource type. 

What could be done, at least in theory, would be to break it into many conformance classes, one for each building block like the `crs` parameter and additional ones to bind these to resources. However, in the current OGC specification modelI this is too fine-grained to be practical with all the overhead that this would introduce. I don't think it would help anyone, if the simple CRS extension would consist of 8 or 10 conformance classes. 

As I have said before, I think a better way would be consider a normative API building block registry from the API building blocks specified in OGC API standards and that would become Common. Not a standard, but a managed registry. These building blocks could then referenced from or copied into OGC API standards - and they could be used by other API designers as well.

**Comment by jerstlouis** [comment]
@cportele I support the idea that Features reference this common CRS building block, e.g. with minimal text specifying how one can bind to it.
I also support the idea that "Common" as a single specification is not well suited to modular building block, and that a registry of conformance classes, with different maturitel levels and standardization status should be part of the solution.

**Comment by cmheazel** [comment]
Take a look at API-Common branch April-2020-Updates.  This version treats /collections as a separate standard, API-Common Part 2.  Note that Part 2 is just a collection of files at this point.  However, API-Common Part 3 is a modified version of the API-Features CRS proposal.  
So, API-Common is a family of standards consisting of the Core, Collections, and CRS.  Additional modules become additional parts of API-Common.

**Comment by cmheazel** [comment]
Also take a look at API-Records. This standard is being written as an extension to API-Common - Core. Rather than replicate Common, it identifies the relevant Requirement Classes and describes how those requirements are addressed in API-Records.  The same approach can be used for any API Module.

**Comment by cportele** [comment]
Meeting 2020-05-11: We have not received other feedback, also not from the new part 3 draft in Common. Let's go ahead based on the current draft as a part 2 of features.
