### ISSUE TITLE
Core: requirements class vs. conformance class

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#301]
I noticed that the dependencies of certain requirements classes link to other requirements classes but the text of the links says "Conformance class" instead "Requirements class".

An example:

![image](https://user-images.githubusercontent.com/11427611/69529183-0dc52880-0f70-11ea-9ee1-232f641ad239.png)

**Comment by cportele** [comment]
Meeting 2019-11-25:  Yes, "Requirements class" would have been correct, but this choice was deliberate as many readers understand "conformance class", but not "requirements class" (unless they are experts of the OGC modular specification policy). Since there is a 1-to-1 relationsship it seemed ok to be intentionally imprecise and use "conformance class" for both to have more intuitive text for the non-OGC-experts. But it is not optimal as "requirements class" is used sometimes, too, including in the table heading. This is a general topic and it would be good to have a consistent approach across OGC specs. @cmheazel will work on a proposal.

**Comment by heidivanparys** [comment]
@cportele @cmheazel 

Wouldn't the consistent approach across OGC specs be to follow the OGC modular specification policy? 🙃

As the OGC modular specification policy is being used as input in the revision of 19105, it would be advantageous if the aforementioned proposal could be ready before the ISO 19105 EC meeting in Japan (9th and 11th of December) so it can be taken into account there.

Regarding "to have more intuitive text for the non-OGC-experts": An explanation regarding the way OGC standards are structured could be added to to the guide to the OGC API - Features in a section called "Introduction to the OGC modular specification". Such a section could also contain figures, e.g. figures like the ones proposed by Denmark in the comments on ISO/CD 19105, if those are accepted.

**Comment by cportele** [comment]
@heidivanparys - The document follows and is consistent with the mod spec policy! Req classes have dependencies to req classes and everything is mirrored 1-to-1 in conformance classes. The only thing is that for simplicity we sometimes write "conformance class X" and mean the "requirements class that is associated with conformance class X".

In practice most spec readers do not read a spec from start to end. They just jump to the specific part they are interested in at the moment. At least this is what I often do and probably most others, too. Most questions that I get on the spec could easily be answered by reading the spec 😏. And most readers are almost certainly not interested in the metamodel underpinning the standards (maybe beside those that design standards), so I think it is important to write standards so readers do not have to be familiar with the ISO Directives or the OGC policies.

I see the shortcomings of what we have done so far (although we never got any question or comment about this yet), but I really would like to avoid explaining the mod spec in the standard.

**Comment by heidivanparys** [comment]
> I really would like to avoid explaining the mod spec in the standard.

I agree. Just to make sure: I meant the guide to the standard, not the standard itself. The guide already contains a section "Introduction to Geospatial" and "Introduction to OpenAPI".

**Comment by cportele** [comment]
Sorry, I missed this part. Yes, the guide would benefit from such a chapter (if we ever get to work on it with all the work on the specs including Common...).

**Comment by cmheazel** [comment]
@heidivanparys @cportele Clause 2, Conformance is particularly weak in this regard. It assumes the reader knows about the Mod Spec.. An unrealistic assumption. I'll update API-Common Clause 2 to better describe the conformance process and add a couple definitions to Clause 4. Look for a pull request by Friday.

**Comment by cportele** [comment]
@cmheazel - Agreed that it is unhelpful to most readers. The current content is mainly driven by the ISO/TC 211 practices (and the OGC standards template). In general, the content in clause 2 is just a summary of the requirements classes and conformance classes in clauses 7+ and annex A with some additional informative language. Even dropping clause 2 altogether would be a purely editorial change (that probably would go unnoticed in general). Maybe that would be an option, too, but it would require a discussion with the Doc Team as it would deviate from the template.

We can simplify the language in OGC land, but in the ISO/TC 211 version we probably have to have something that is similar to the current text.

I will wait for the PR, but I would be concerned about discussing the conformance process in the standards (each standard) and including definitions not related to the technical scope of the document.

**Comment by cmheazel** [comment]
@cportele respectfully disagree. One could argue that the requirements are the only normative part of the standard. Therefor, the criteria for meeting those requirements is within the technical scope of the document. I'm thinking of a short section targeting developers and test engineers. Just what they need to know to correctly use the standard and no more.

**Comment by cmheazel** [comment]
See "Updates-from-API-Features" branch of API-Common.

Added:
 - Mod Spec as a normative document
 - Terms and definitions related to conformance
 - Added a discussion of conformance to clause 2
Also: updated text of requirements classes to have dependencies on requirements classes, not conformance classes.

Finally, I find that the Mod Spec is not clear on the difference between a conformance class and a requirements class. In my discussion I assert that conformance classes describe capabilities (or functionality) while the requirements classes define how to validate that capability. I believe this is in-line with the intent of the Mod Spec if not the wording.

**Comment by cportele** [comment]
The added text looks fine, but I still think this is heading into the wrong direction.

* The Mod Spec is *not* a normative document for any of the OGC standards. No requirements class has a dependency on the Mod Spec and thus it is not a normative reference. It does not really matter, if the document is listed in that clause as the reference has no effect (and OGC has always been lax about what is listed in that clause). If OGC API Common will ever go to ISO, they will remove the reference before publication.
* This just basically adds more boilerplate text that is not related to the scope of the standard and makes it harder to see the content and the definitions that are relevant for the standard.

What I would propose is to change the OGC standards template to start the terms and definitions clause to reference the Mod Spec and its definitions instead of the current reference to OWS Common (I had a look and I don't see how the OWS Common definitions are a good basis for the OGC API standards). Or just do it in OGC API Common and the other OGC API standards then reference the definitions in Common.

> In my discussion I assert that conformance classes describe capabilities (or functionality) while the requirements classes define how to validate that capability.

Have you swapped the terms here? A requirements class defines requirements (required capabilities), a conformance class how to assert / test that an instance is in conformity with the associated requirements class.

**Comment by cmheazel** [comment]
It's a circular reference.
A requirements class defines requirements. Requirements for what? Answer: an API module. How do we identify an API module?  Answer: by its conformance class. So a conformance class identifies the API Module, a concept, as well as the test procedure for validating the normative requirements for that module. Isn't that confusing?

The Mod Spec doesn't deal with modularity at the conceptual level. But API modules are the foundation of our API approach. Core, Filter, Transaction, these are all concepts which encompass both normative and informative parts. Their scope is far more than just a conformance test.

**Comment by cportele** [comment]
@cmheazel - You have lost me here.

> It's a circular reference. ... How do we identify an API module? Answer: by its conformance class. So a conformance class identifies the API Module, a concept, as well as the test procedure for validating the normative requirements for that module. 

The conformance class is only about the tests (for a requirements class), nothing else.

Since there is a one-to-one relationship between requirements and conformance class, if you identify one of them you implicitly identify also the other class.

The Mod Spec is not about "concepts" per se, it is about the normative testable statements that make up a specification plus their tests. All relevant concepts must be represented in normative statements.

> The Mod Spec doesn't deal with modularity at the conceptual level. But API modules are the foundation of our API approach. Core, Filter, Transaction, these are all concepts which encompass both normative and informative parts. Their scope is far more than just a conformance test.

I do not understand what you are trying to say or how this is related to the issue.

**Comment by cmheazel** [comment]
In the API-Common update:  Requirements Classes have dependencies on Requirements Classes.  Conformance Test Classes have dependencies on Conformance Test Classes, Conformance Test Classes identify the Requirements Class they are testing.  The use of the term Conformance Class is left unchanged when used outside of the scope of an ATS or RC.

Also, definitions from 08-131 have been included, 08-131 has been added to the bibliography and removed from the list of normative documents.

And finally, the Mod Spec discussion has been removed from Clause 2 (conformance)
