### ISSUE TITLE
Question regarding distributions and DCAT v2

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#305]
When a Web API implements the following requirements classes:

- Requirements Class "GeoJSON"
- Requirements Class "Geography Markup Language (GML), Simple Features Profile, Level 0"

is that Web API then one distribution (using 2 formats) of a particular dataset, or two distributions (each using 1 format)?

From clause 7.1 (highlighting is mine):

> A server that implements this conformance class provides access to the features in a dataset. In other words, **the API is a distribution of that dataset**. A file download, for example, would be another distribution.

And this is essentially the same as the following quote from the [Data Catalog Vocabulary from 2014](https://www.w3.org/TR/2014/REC-vocab-dcat-20140116/):

> For example, a dataset that is available via an API can be defined as an instance of dcat:Dataset and the API can be defined as an instance of dcat:Distribution.

Related to this: [DCAT version 2](https://w3c.github.io/dxwg/dcat/) is currently being developed, introducing the concept of a [DataService](https://w3c.github.io/dxwg/dcat/#Class:Data_Service)

> A data service is a collection of operations accessible through an interface (API) that provide access to one or more datasets or data processing functions. 

See a longer discussion regarding some of the consequences in https://github.com/w3c/dxwg/issues/1055

So in general, I am wondering if the current standard OGC API - Features - Part 1: Core

1. has too much informative information in it describing how it can be used together with DCAT
2. is, as a result, too tightly coupled to the DCAT specification (from 2014)
3. which in turn may give issues when DCAT v2 is published (I don't know the exact roadmap for DCAT v2)

I think some of this information could be removed from the standard and written in the guide instead.

**Comment by cportele** [comment]
I do not see issues with DCAT v2 at the moment. OGC API Features references DCAT v1 and this will continue to be consistent. Even if the intent of the DCAT v1 authors may have been that every distribution was of a single format, I don't think DCAT v1 ever says that and on the other hand it is explicit that an API can be a single distribution.

That said, as a change in the definition of "distribution" in DCAT v2 would not impact existing APIs (as far as I understand it, except maybe their schema.org annotations in HTML) and would mainly impact metadata in catalogues, it should be possible to reflect such a change in a future revision of the standard.

We originally included the informative wording about distributions because pointing these aspects out seemed relevant for the geo-community and clarifies how things map to the "Web view" that is captured in DCAT v1. I think the text has or at least had a role, and yes, some of the language could be removed / moved outside of the standard.

**Comment by jvanulde** [comment]
Can one say that an API is a dcat:DataService with multiple dcat:Dataset, each corresponding to a representation (e.g. GeoJSON, GML)? Or is it more consistent with the current state to say that an API is dcat:Dataset with multiple dcat:Distribution, one for each representation (e.g. GeoJSON, GML)?

**Comment by cportele** [comment]
I have not followed the recent DCAT v2 discussions on dcat:DataService, so I cannot comment on the relationship to it.

However:

* A Web API that implements Part 1 of OGC API Features (and nothing else) is in general not a dcat:Dataset itself as the API is just one (or more) distributions of a dataset. The dataset may have other distirbutions, too, like direct downloads that are outside of the API.
* That said, in ldproxy we currently add schema:Dataset by default to the landing page (with the landing page URI) since in general there is no canonical dataset URI that could be reused. The proper implementation would be a dataset resource somewhere that has links to all its distributions (and the relevant dataset metadata). This could be the API landing page, but that would depend on how the data provider manages its resources.
* Based on the DXWG issue referenced above, it seems like the DXWG is changing the definition of distribution in v2 in a non-backwards compatible way and every representation provided by an API would have to be a separate distribution in v2. That would leave at least two options:
  * Each combination of the `.../collections/{collectionId}/items` (accessURL) and supported format (mediaType) could be a DCAT v2 distribution. However, this is misleading as this is a URL for a subset of the dataset (unless there is only one collection). Since there a no multiplicities stated AFAIK maybe the distribution could have multiple accessURLs, but my guess from the discussion in the DXWG issue is that the expectation is that there is only a single accessURL. (If that is the case, it is a general shortcoming as direct downloads of a spatial dataset will often be split into separate files per feature type. I also exclude the option to consider each collection a separate dataset as this obviously does not reflect the view of the data provider.)
  * There is a distribution for each format (mediaType) and the accessURL should probably be the `.../collections` URI. I think I wouldn't use the landing page URI in that case, because if the API has many more capabilities than just the Part 1 conformance classes it will be increasingly difficult to find the links to the data as there will be many more links to other resources. This option is probably closer to the DCAT v2 model.
* If the API implements only Part 1 of OGC API Features it will provide access to a single feature dataset (dcat:Dataset). Support for multiple datasets is something that is in scope for extensions.

**Comment by cportele** [comment]
After some more thoughts and reading through the new DCAT2 draft, I now tend to agree with the proposal to change the wording so that this is not coupled to the DCAT use of distribution, but so that a DCAT2 use would still be consistent with the wording in the OGC API Features spec. I think a few editorial changes should be sufficient. I will assign this to me and work on a pull request that we then can review.
