### ISSUE TITLE
OpenAPI Specification 3.0.3

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#339]
Change normative reference to the new corrigendum

**Comment by heidivanparys** [comment]
What happens when OAI releases a version 3.0.4? According to the text (and the ISO guidelines), 3.0.4 will not apply as the reference is dated.

> The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

I would like to suggest the following:

[OpenAPI] OpenAPI Initiative: **OpenAPI Specification.**  Version 3.0. The latest patch version at the time of publication of this standard was 3.0.3, available from [http://spec.openapis.org/oas/v3.0.3](http://spec.openapis.org/oas/v3.0.3).

This also takes care of:

- OpenAPI Initiative instead of Open API Initiative
- link to the official specification (linked to from https://www.openapis.org/ as well), instead of a link to GitHub

**Comment by cportele** [comment]
I like that and will use the proposal, thank! OGC has no concept of undated references so far (I think), but the approach is consistent with the versioning policy and how corrigenda are treated (as long as semantic versioning is used).
