### ISSUE TITLE
Question regarding TRS (Core)

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#362]
Should there be a requirement similar to [/req/core/crs84](http://docs.opengeospatial.org/DRAFTS/17-069r4.html#req_core_crs84) for the temporal reference system?

So that e.g. temporal extents cannot be described in other TRSs than http://www.opengis.net/def/uom/ISO-8601/0/Gregorian?

**Comment by cportele** [comment]
For the temporal extent, the Gregorian calendar is already the default reference system just like CRS84 is for the spatial extent, there is no difference between spatial and temporal as far as I can see. See [7.13.2](http://docs.opengeospatial.org/DRAFTS/17-069r4.html#_response_4).

`/req/core/crs84` is about spatial geometries, i.e., mainly about the spatial geometries of the features returned by the API. So, the question is whether we should add a similar requirement that any date/time value in the feature response is in the Gregorian calendar. We can only add such a requirement in the Core, if it already exists implicitly and we would add it for clarity. Otherwise it could break existing implementations.

I think we haven't made a similar requirement for the temporal reference system to be used in feature representations, because there have been far less issues related to temporal reference systems compared to all the spatial CRS discussions. There is already the requirement that for temporal feature data the API has to support the Gregorian calendar in all queries, because the `datetime` parameter is and will always be in the Gregorian calendar as it is based on ISO 8601. As a result, I think most implementations use the Gregorian calendar and ISO 8601/RFC  3339 also in the responses.

It is correct, the server could still return the temporal feature properties in another temporal reference system and it would not violate any current requirement, but that has not raised an issue so far. 

Because of what was said above, I do not think that we can or should add a requirement, but we could add a paragraph in [7.11](http://docs.opengeospatial.org/DRAFTS/17-069r4.html#_coordinate_reference_systems) to discuss this and add a recommendation to return temporal properties in the Gregorian calendar and with date/time representations conforming to RFC 3339.

Other views/comments?

**Comment by cportele** [comment]
Meeting 2020-04-27: Add an explanatory paragraph in 7.11 as proposed above. Take https://github.com/opengeospatial/oapi_common/blob/April-2020-Updates/collections/clause_6_conventions.adoc into account. Action CP.
