### ISSUE TITLE
Review Comment: Recommended URI Format

### ISSUE THREAD

**Issue by cmorriscmps** [opengeospatial/ogcapi-features#375]
I would prefer to see the term authority renamed to registry in the recommended URI format (recommendation 1).

The term authority may cause confusion if one authority publishes multiple CRS registries.  In fact, it’s already an issue because the term authority doesn’t adequately describe the values that are currently in use as listed at http://www.opengis.net/def/crs.  “AUTO” is certainly not an authority, but I think it would be fair to say that AUTO, EPSG, and OGC are all registries.

The recommendation also states that “0” can be used for the latest version or if the version is unknown.  It’s worth pointing out that resolving these URIs doesn’t currently work.  For example, http://www.opengis.net/def/crs/OGC/1.3/CRS84 resolves fine, but http://www.opengis.net/def/crs/OGC/0/CRS84 returns an exception.  I would suggest fixing this before publishing the standard.

**Comment by cportele** [comment]
"authority" is the name used for the element in the [policies for the OGC-definition-URIs](https://docs.opengeospatial.org/pol/09-048r5.html#_production_rule_for_specification_element_names). But indeed AUTO is not a registered authority (http://www.opengis.net/def/auth), so we need to clarify this with the OGC Naming Authority.

We need to clarify the interpretation of "0" with the OGC Naming Authority and align the text with the behaviour of the OGC Definitions Server (or vice versa).

@ghobona - Any comments on this?

**Comment by ghobona** [comment]
Section 6.7.3.4 of the WMS 1.3 standard (OGC 06-042) is titled "AUTO2 namespace for CRS" and says:

_The “AUTO2” namespace is used for “automatic” coordinate reference systems; that is, for a class of CRSs that include a user-selected centre of projection. Several “AUTO2” CRSs are defined in Annex B._

We need to treat AUTO(2) as an authority in order to maintain backwards compatibility. So perhaps we should register both AUTO and AUTO2 in http://www.opengis.net/def/auth ?

Regarding "0", Section 6.2 of the definitions policy document (OGC 09-048r5) says  "use 0 for un-versioned names". In many cases the 0 appears superfluous, so we should consider relaxing the policy to make the segment optional. This might be worth discussing at the June Virtual TC meeting.

**Comment by cportele** [comment]
Meeting 2020-05-11: @cportele to resolve this based on the discussion above, including with the OGC-NA.

**Comment by cportele** [comment]
Thanks @ghobona - Yes, I think that AUTO and AUTO2 should be registered as authorities in the OGC Definitions server to be consistent.

**Comment by cportele** [comment]
Sorry, I pushed the edits to the master branch, not a new branch for a pull request. I reopen the issue, but leave the changes in master for now.

**Comment by cportele** [comment]
Keep it open until we have resolved the authority registration.

**Comment by ghobona** [comment]
**2021-03-22 OGC-NA meeting**

OGC-NA recognises that AUTO and AUTO2 have been in use for a long time and therefore does not object to AUTO and AUTO2 being registered as Authorities.

OGC-NA however observes that this is an unusual use of the term 'authority'.

Features API SWG, please liaise with @rob-metalinkage regarding creating appropriate metadata to describe AUTO and AUTO2.

@ghobona will provide a reference to authority policy.

**Comment by cportele** [comment]
Thanks @ghobona. OGC API Features does not have specific requirements how AUTO and AUTO2 CRS URIs are represented. The right group for this should be the CRS SWD/DWG. 

Since there is now an issue in the OGC NA repository, I think we can close this issue here (we can discuss in the next SWG meeting).

**Comment by cportele** [comment]
2021-05-10: Issue can be closed
