### ISSUE TITLE
Native CRS instead of Storage CRS

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-features#420]
There was a discussion in the WCS SWG today (2020-07-22) regarding whether to use the term "native CRS" or "storage CRS"

If you run these queries in a search engine:

"native CRS" site:ogc.org

"storage CRS" site:ogc.org

... the results suggest that "native CRS" is the term that has been used more, historically.

**Comment by cportele** [comment]
I would have no problem with "native CRS" instead of "storage CRS". If we use Google search as an indicator, both terms do not have a strong history in OGC (4 and 21 hits only).

A procedural aspect: Since Part 2 is no longer in control of the SWG, that comment would have to be made as part of the TC approval process.

**Comment by lieberjosh** [comment]
Prefer “native” as it connects data quality parameters to an original CRS that may subsequently be altered by interpolation during re-projection.

**Comment by pvretano** [comment]
I have no problem with either term ...

**Comment by ghobona** [comment]
Cc @ogcscotts

**Comment by cportele** [comment]
Since no vote during the TC approval vote includes a comment on this, I guess we can close this issue and stick to `storageCrs`?

**Comment by ghobona** [comment]
@cportele Agreed. The issue is OBE and can be closed.
