### ISSUE TITLE
Spatial filters supporting WKT

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-features#425]
EDR inherits BBox from Common, but also [supports](http://docs.opengeospatial.org/DRAFTS/19-086.html#parameters-section) WKT in queries through the `coords` parameter. 

Could such a capability be supported in the Filtering and CQL extension of OGC API - Features?

Please coordinate with the EDR API SWG on this.

This is a Cross-SWG Discussion topic.

**Comment by cportele** [comment]
In my view we should not specify a `coords` parameter on the Features resource. 

We want to avoid too many options to request the same results. It was a deliberate choice to support the simple filtering options in core (`bbox`, `datetime` and property-specific parameters). While all queries based on these options could also be expressed as a CQL filter expression, this redundancy has been considered acceptable, because it avoids that APIs that do not need or want to expose more advanced filtering have to implement something like CQL. But any Features request with a hypothetical `coords` parameter can easily can written as a CQL filter and once you want to support something WKT-based expressions this should be done through the `filter` parameter. Of course, if an implementation wants to add support for `coords` it can do it, it just does not belong into the Features standards.

In EDR this is different as `coords` (the sampling geometry) is for EDR what `bbox` is for Features - the minimal required spatial filtering capability. So, using `coords` in EDR looks fine to me. It just doesn't have any implications for the Features standards.

cc @dblodgett-usgs

**Comment by dblodgett-usgs** [comment]
That's right @cportele -- in EDR, we have a "locations" end point that does not return pageable items but does support querying by coords. We are using items out of the box -- so to speak -- from Features as a sort of catalog of EDR query end-points. Including a way to discover available locations. 

I think it's the right decision to keep features simple and avoid adding complex spatial queries in this way.

**Comment by cportele** [comment]
Features API SWG Meeting 2020-09-14: We consider the discussion done. Nothing to add to the comments above.
