### ISSUE TITLE
Core: recommendations on next links

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#428]
Currently there are recommendations on the use of `next` links:

> A 200-response SHOULD include a link to the next "page" (relation: next), if more features have been selected than returned in the response.

> The number of features in a response to a next link SHOULD follow the same rules as for the response to the original query and again include a next link, if there are more features in the selection that have not yet been returned.

How about the opposite? Are there any guidelines for that? Such as:

A 200-response SHOULD NOT include a link to the next "page" (relation: next), if all features that have been selected are returned in the response.

The number of features in a response to a next link SHOULD follow the same rules as for the response to the original query and not include a next link, if all features in the selection have been returned already.

What is good practice?

**Comment by pvretano** [comment]
@heidivanparys What other options do you envision in the case where there are no more features in the result set to present? To me the current guidance seems pretty clear since it says "... include the next link, [**IF**] there are more features ..." which implies that if there no more features, don't include the link.  I am not opposed to being explicit about it as you propose; I just want to make sure we did not miss another possible way to handle the situation.

**Comment by cportele** [comment]
I don't think additional text is needed. Isn't it obvious that a next link does not add anything, if the server knows that there is no "next" resource that could be linked to? Where would a next link point to, if there is no next page?

**Comment by heidivanparys** [comment]
I am currently reviewing an API that returns the following for `{root}/collections/{collectionId}/items`:

```
{
    "type": "FeatureCollection",
    "features": [
        ...
    ],
    "timeStamp": "2020-08-14T06:59:19Z",
    "numberReturned": 6,
    "links": [
        {
            "href": "{root}/collections/{collectionId}/items",
            "rel": "self",
            "type": "application/geo+json",
            "title": "This document"
        },
        {
            "href": "{root}/collections/{collectionId}/items?offset=6",
            "rel": "next",
            "type": "application/geo+json",
            "title": "Next set of results"
        }
    ]
}
```

and the following for `{root}/collections/{collectionId}/items?offset=6`:

```
{
    "type": "FeatureCollection",
    "features": [],
    "timeStamp": "2020-08-14T07:00:02Z",
    "numberReturned": 0,
    "links": [
        {
            "href": "{root}/collections/{collectionId}/items?offset=6",
            "rel": "self",
            "type": "application/geo+json",
            "title": "This document"
        }
    ]
}
```

> To me the current guidance seems pretty clear since it says "... include the next link, [IF] there are more features ..." which implies that if there no more features, don't include the link.

Those two statements are not logically equivalent, see e.g the explanation at [https://www.thoughtco.com/converse-contrapositive-and-inverse-3126458](https://www.thoughtco.com/converse-contrapositive-and-inverse-3126458)

> How about the opposite? Are there any guidelines for that?

Using the proper mathematical terms, the question is: "How about the inverse, are there any guidelines for that?"

**Comment by jampukka** [comment]
I see, the current guidance doesn't clearly forbid adding a `next` link in the case that there are no more (or any) features left. The intent is to be able to signal that there are no more features and that the response is now complete. Most clients are written with logic `while next link exists then fetch more` in mind.

Change the `if` to `if and only if`? Or is that too limiting for implementations? I don't really mind the API under review including the next link in the first response (other than that it is against the original intent of the guidance) but the second response will cause an infinite loop in the worst case with most clients.

**Comment by cportele** [comment]
I think we have a similar behaviour in ldproxy. If the request has limit n and the query to the backend datastore returns n features there is no way for the server to know, if there are more features or not (in most cases there will be more features), unless the total number of matches is also computed, which may be too costly. So the next link is added if the response has n features and if there are no more, the next link will return 0 features and no next link. That behaviour is consistent with the spec and will not create problems with clients that do paging.

**Comment by pvretano** [comment]
@heidivanparys  thanks for the link to thoughtco.com; never heard of that site ... very interesting.  Here are my observations ... which may be wrong of course ...
I think in this situation the statements are logically equivalent  because this situation is more constrained than sidewalks, wetness, rain and the possibility that the sidewalk may have been made wet by some other means than rain.
There are only two possibilities here ... no?  Either the server knows that it has returned the complete result set or it does not.  If it knows that it has returned the complete result set then it should not include the next link because there is nothing to link to.  If it does not know that it has returned the complete result set then it should include the next link.  When that "next" link is resolved and the the complete result has in fact been returned (because there are no more features to present), the server can return an empty collection with no next link because the server now knows for sure that there are no  more features to return.
In the example you give above, the server knows that it has returned the complete result set after the first request and so it should not include the next link ... although doing so does not break paging as @cportele has pointed out.  I wonder, would this be considered a bug by a CITE test (i.e. server knows that it has returned the complete result set but still includes next link)?

**Comment by cportele** [comment]
2020-08-16: We should make it clear that the example is a valid case in the regular informative text. This will make the expectations explicit and clear. @cportele to draft a PR.
