### ISSUE TITLE
Wording of ATS A.2.8 might be a bit ambiguous ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#574]
The wording of A.2.8 says that "{featureId} is the id property of the feature".  This may actually be ambiguous wording.  Consider the following GeoJSON feature:
```
    {
      "type": "Feature",
      "id": "CWFID.COASTL_1M.0.9",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [-152.868927,-77.38630676 ],[-152.8668365,-77.38627625],
          [-152.8461456,-77.39202881],[-152.8418884,-77.39865875],
          [-152.8575897,-77.4036026],[-152.85849,-77.40388489],
          [-152.960907,-77.41478729],[-153.0134583,-77.41537476],
          [-153.0023499,-77.40129852],[-152.9791565,-77.39255524],
          [-152.947464,-77.3874054],[-152.868927,-77.38630676]
        ]
      },
      "properties": {
        "id": 4628,
        "f_code": "BA010",
        "acc": 2,
        "exs": 44,
        "tile_id": 713,
        "edg_id": 41
      }
```
There is the top level "id" and then there is an "id" property.  The identifier of the feature is actually the top level "id" but the way the test is worded one might think that property.id is the feature identifier.  A similar ambiguity might exist with GML too with gml:id and an element named "id".  Perhaps we can think of some better wording ...

**Comment by rouault** [comment]
Perhaps "{featureId} is the id member of the feature" (using the terminology of https://www.json.org/json-en.html ) ?

**Comment by cportele** [comment]
Since the unambiguous wording will depend on the feature encoding / media type, we probably need to clarify this for each encoding conformance class.

For the featureId:

* GeoJSON: "`{featureId}` is the `id` member of the GeoJSON feature object." (based on the suggestion by @rouault)
* GML-SF0/SF2: "`{featureId}` is the `gml:id` XML attribute of the GML feature element."
* HTML: Since we don't prescribe how features are encoded in HTML, I don't think we can test this in the HTML encoding.

**Comment by pvretano** [comment]
@cportele that is what I was thinking too ...
