### ISSUE TITLE
Consider splitting up Simple CQL into multiple conformance classes

### ISSUE THREAD

**Issue by philvarner** [opengeospatial/ogcapi-features#579]
In the context of STAC Items, the biggest piece missing from the Part 1 "items" endpoint is a *formalized* mechanism for filtering based on fields in the Feature/Item's Properties. Implementations can support arbitrary query parameters to support this, but there's no "queryables" mechanism to discover what fields can be filtered on. For example, a common filter criteria is cloud cover, and there's no well-defined way to express a simple `cloud_cover <= 10`. An implementer may desire to only support this one predicate, and is satisfied with using the existing `datetime` and `bbox` for spatial and temporal filtering. 

However, with the current Simple CQL conformance class, an implementer would be forced to support more than just simple comparison operations (e.g., gt, lt, etc.) and would also need to support all the logical operators and the more complex comparison operators, IN, LIKE, BETWEEN and IS NULL. (They would not *actually* need to implement INTERSECTS or ANYINTERACTS if they don't advertise any queryables of spatial or temporal types) This makes conforming to the CQL spec much more difficult that the needs of the implementation require, and will likely lead to implementers doing something proprietary or, even worse, only partially implementing CQL but advertising that it is conformant!

Additionally, I don't like the use of "Simple" for the class, as it is still a pretty complex language. I think a word like "basic" would be more appropriate here. Also, this class has "CQL" in the name, whereas as none of the other "operator" classes do.

I'd like to propose to divide Simple CQL into these separate conformance classes:

- Basic Comparison Operators - `=,<,<=. >, >=`
- Enhanced Comparison Operators - `IN, LIKE, BETWEEN, IS NULL`
- Logical Operators - `and, or, not` (these could also go into a "basic logical and comparison operators" class, but it feels a little cleaner to split them out)
- Basic Spatial Operators - `intersects` 
- Basic Temporal Operators - `anyinteracts`

While this does introduce some overhead, in that now an implementation has to advertise 5 classes instead of 1, I think there is a large benefit in allowing implementations with limited needs to properly implement a subset of these conformance classes, instead of simply not conforming to CQL at all. I think that this will result in both more robust implementations and provide an "on-ramp" for an implemenation to support more and more of the CQL conformance classes over time.

Thanks for your consideration of this!

**Comment by pvretano** [comment]
@philvarner we have already been discussing removing the spatial and temporal operators for simple CQL altogether and simply having two classes (spatial operators, temporal operators) where all these operators reside.  This was motivated by the fact that features already provides bbox and date-time for simple spatial and temporal filtering so there is no used in repeating that in "simple" CQL. 
I am not opposed to taking that logic one step further and breaking the operators down into finer classes.  I don't think it would be such a big deal for implementations ... 1 URL, 5 URLs in the conformance sections ... not big deal!  Would be a lot of document works but ... meh! ;)

**Comment by cholmes** [comment]
I agree with the logic of having the most 'basic' level enabling simple comparisons. That's one that seems like it could almost be in 'core', or at least is the clear 'next step', and shouldn't force people to do a whole lot more.

I think the key is to get the 'groupings' right. I believe as Phil laid them out it'll be 10 total classes, the five core plus functions, arithmetic expressions, arrays, enhanced spatial and enhanced temporal. 

I could see whittling that down some, if we thought ten was a lot. Put logical in basic comparisons, and just have one 'spatial' and one 'temporal'. I think I do like 'enhanced comparison' as its own - there's a lot of extras in there that take more work. 

Spatial I think I do like having 'intersects' and 'enhanced spatial operators' separated out. Intersects get you actual geometries vs just the core, and many spatial backends don't implement the full suite of spatial operators. In STAC's query language we just had 'intersects' (above what we got from features API).

Temporal I honestly still don't understand, but perhaps should try to dig in. But it seems like the basic comparisons should handle time? I don't really understand what anyinteracts does, but if basic comparisons handle time then there doesn't seem to be much value in having just one temporal operation as its own class. 

I guess I don't see much that'd be wrong about having 9 or 10 conformance classes. I think temporal is the one I'd consider just doing one class of temporal operators, but I also don't fully understand it.

I do like this makes for an easier 'on ramp'. I would love us to consider actually breaking the spec into smaller pieces, so we don't present people with a 99 page document when they first hear about CQL. I likely have some funded hours to be able to help with document work if people are up for that (or I can focus my time on the 'guide'/'intro' texts to accompany the core spec text).

**Comment by philvarner** [comment]
> @philvarner we have already been discussing removing the spatial and temporal operators for simple CQL altogether and simply having two classes (spatial operators, temporal operators) where all these operators reside. This was motivated by the fact that features already provides bbox and date-time for simple spatial and temporal filtering so there is no use in duplicating those capabilities in "simple" CQL.

I would prefer to also split the spatial and temporal operators into basic (intersects, anyinteracts) and Enhanced.  For spatial operators, one practical reason is that Elasticsearch only supports intersects, so if they were all in a single spatial class, someone using Elastic could not implement it. For temporal, I think most use cases only need anyinteracts, and the other ones just add complexity that isn't necessary for many implementations. 

I would also argue against there being "no use" for intersects in simple CQL -- I think this will be used commonly in scientific applications. bbox is obviously restricted to a rectangle, and that doesn't work well for many of the scientific use cases i've encountered -- for example, several different small areas or points over a large geographic areas, or a complex shape whose bounding box has significantly more area that the shape itself. 


> I am not opposed to taking that logic one step further and breaking the operators down into finer classes. I don't think it would be such a big deal for implementations ... 1 URL, 5 URLs in the conformance sections ... not big deal! Would be a lot of document work though ... but ... meh! ;)

sounds good to me!

**Comment by philvarner** [comment]
> Temporal I honestly still don't understand, but perhaps should try to dig in. But it seems like the basic comparisons should handle time? I don't really understand what anyinteracts does, but if basic comparisons handle time then there doesn't seem to be much value in having just one temporal operation as its own class.

anyinteracts is effectively "do these two datetimes or intervals have any intersection with each other", and is effectively the time equivalent to spatial intersects. It's what the existing `datetime` query parameter semantics are now.

**Comment by cholmes** [comment]
> anyinteracts is effectively "do these two datetimes or intervals have any intersection with each other", and is effectively the time equivalent to spatial intersects. It's what the existing datetime query parameter semantics are now.

Then that would seem to me to indicate that a basic class with just 'anyinteracts' isn't so valuable since you can accomplish that with `datetime` in core already? Or am I misunderstanding? If so then I'd lean towards just a single 'time' conformance class (and then have spatial split in 2, that one I agree there's value in just 'intersects' above what features api core offers).

**Comment by pvretano** [comment]
@cholmes correct ... which is why in the SWG we discussed just removing both intersect and anyinteracts from SimpleCQL and putting those operators into the Extended Spatial Operators and Extended Temporal Operators classes (and then dropping "Extended").
I believe that @philvarner is arguing that there is still value in having  simpler spatial and temporal operator classes and also having more advanced spatial and temporal operator classes to accommodate various level of requirement from simple to more complex.

In the old OGC Filter specification we got around this be simply letting a server list which operators the server supported .... [see here](http://schemas.opengis.net/filter/2.0/examples/3.2.1/filter19.xml).

Its starting to sound like this idea might be usefully translated into the OGC APIs since no matter how we decide to partition the operators, someone is not going to be happy! ;)

**Comment by philvarner** [comment]
> > anyinteracts is effectively "do these two datetimes or intervals have any intersection with each other", and is effectively the time equivalent to spatial intersects. It's what the existing datetime query parameter semantics are now.
> 
> Then that would seem to me to indicate that a basic class with just 'anyinteracts' isn't so valuable since you can accomplish that with `datetime` in core already? Or am I misunderstanding? If so then I'd lean towards just a single 'time' conformance class (and then have spatial split in 2, that one I agree there's value in just 'intersects' above what features api core offers).

The operation is the same, but you can't compose them with logical operators in core `datetime`.  This is useful for queries  that do period-over-period comparisons, e.g., this day in each of 5 years. I think there's also value in being able to push all individual query params into just a unified CQL statement instead of having some filters in each.

**Comment by jisantuc** [comment]
> you can't compose them with logical operators in core `datetime`

^^ that to me seems like the important part of CQL -- since it's the only place where this kind of expressiveness is available (at least in STAC API spec) i don't think it's bad if specific combinations of parameters happen to duplicate functionality elsewhere.

Multiple conformance classes also makes sense to me -- as already talked about with ElasticSearch there are going to be queries that are easier / more difficult to support in different settings, and letting people build their conformance a la carte will be nicer than the alternatives I think. I don't have much of a horse in the race of how finely things are sliced -- Franklin will probably implement all of them, but I still think it's valuable not to have to.

**Comment by cholmes** [comment]
> Its starting to sound like this idea might be usefully translated into the OGC APIs since no matter how we decide to partition the operators, someone is not going to be happy! ;)

I think I prefer us to actually think through the best grouping, as I think we can get to groupings that make most people happy, and I see value in chunks of functionality. This can also help implementors figure out what to prioritize.

**Comment by cholmes** [comment]
>> Then that would seem to me to indicate that a basic class with just 'anyinteracts' isn't so valuable since you can accomplish that with datetime in core already? Or am I misunderstanding? If so then I'd lean towards just a single 'time' conformance class (and then have spatial split in 2, that one I agree there's value in just 'intersects' above what features api core offers).

> The operation is the same, but you can't compose them with logical operators in core datetime. This is useful for queries that do period-over-period comparisons, e.g., this day in each of 5 years. I think there's also value in being able to push all individual query params into just a unified CQL statement instead of having some filters in each.

Ah, gotcha. Cool, makes sense to me then.

**Comment by jampukka** [comment]
I prefer groups/classes over listing each operator separately.

Like @cholmes and @philvarner I also think there's value in intersects being separate from rest of the spatial operators as it's the most commonly used and also supported by the backend plus it works with geometries not just envelopes.

**Comment by cportele** [comment]
Meeting 2021-06-21: We do not want the conformance classes too fine grained (this did not work well in Filter Encoding with the filter capabilities). We have already moved `intersects` and `anyinteracts` to the spatial/temporal conformance class. We might also move IN, LIKE and BETWEEN to an enhanced comparison operator conformance class, but currently think that the basic comparison operators, the logical operators and IS NULL should be in "Simple CQL". @cportele to make a proposal. We are aware that we will never be able to make it correct for everyone.

Question during the discussion: Can `prop = NULL` be used to test for null? We think this is not consistently defined in SQL, @pvretano will check.

**Comment by cportele** [comment]
Proposal for the CQL2 conformance classes based on the discussion:

* logical expressions (AND/OR/NOT), sub-expressions and basic comparison predicates on strings/numbers/boolean/instants with properties as first operand, literals as second operand - "BasicCQL"
* LIKE/BETWEEN/IN operators, UPPER()/LOWER() - "Advanced comparison predicates"
* spatial predicates
* temporal predicates
* array predicates
* literals also as first operand, properties also as second+ operand - "???"
* (custom) functions
* arithmetic expressions

**Comment by philvarner** [comment]
Could you explain what CQL2 is?

I think that this proposal doesn't account for datastores that don't support all the spatial and temporal predicates, and that's there's a need for classes that only support INTERSECTS and ANYINTERACTS but not any of the other predicates.

**Comment by philvarner** [comment]
Also, to clarify "IS NULL" will be part of "BasicSQL"?

**Comment by philvarner** [comment]
I would prefer to have "ILIKE" in Advanced Comparison Operators rather than UPPER()/LOWER() functions, so that an implementation can entirely ignore parsing functions in expressions.

**Comment by cportele** [comment]
Meeting 2021-07-05: general agreement that the breakdown makes sense.

@philvarner - regarding your comments/questions: @pvretano will respond to the first comment. Regarding IS NULL, yes it is the idea to have it in BasicCQL, it is seems to us to be an important basic test. Regarding the approach to LIKE (function or ILIKE etc, this is discussed in #541 and related issues and we should continue that discussion there).

**Comment by pvretano** [comment]
@philvarner Part 3 was derived from the the CQL that was defined in [old Catalog standard](https://www.ogc.org/standards/cat) and for a long time Part 3 was conformance to CQL from the [old Catalog standard](https://www.ogc.org/standards/cat) so it was safe to use the term "CQL" to refer to either.  However, with all the recent changes, the two CQLs are diverging quite a bit and so the SWG felt that we should refer to the CQL from Part 3 as CQL2 to avoid and confusion.

@philvarner with regard to supporting INTERSECTS and ANYINTERACTS, the feeling of the SWG was that Part 1 already defines bbox and datetime that take care of basic spatial and temporal filtering and there is no use in duplicating that capability in the BasicCQL conformance class.  There might be a discussion point for further sub-dividing the spatial and temporal predicate conformance classes into basic spatial/temporal and then the rest.  That is something we will need to discuss at the next SWG meeting.

**Comment by philvarner** [comment]
> @philvarner Part 3 was derived from the the CQL that was defined in [old Catalog standard](https://www.ogc.org/standards/cat) and for a long time Part 3 was conformant to CQL from the [old Catalog standard](https://www.ogc.org/standards/cat) so it was safe to use the term "CQL" to refer to either. However, with all the recent changes, the two CQLs are diverging quite a bit and so the SWG felt that we should refer to the CQL from Part 3 as CQL2 to avoid any confusion.

Thanks for the details!

> @philvarner with regard to supporting INTERSECTS and ANYINTERACTS, the feeling of the SWG was that Part 1 already defines bbox and datetime that take care of basic spatial and temporal filtering and there is no use in duplicating that capability in the BasicCQL conformance class. There might be a discussion point for further sub-dividing the spatial and temporal predicate conformance classes into basic spatial/temporal and then the rest. That is something we will need to discuss at the next SWG meeting.

I am in favor of dividing them. I'm going to break these up differently in the STAC API Filter Extension conformance classes for now, but hopefully we'll re-align at some point in the future.

The two main issues I see are (1_ that bboxes are too course-grained for many applications, for example, where scientists have a precise shapefile of the area of interest, and (2) the bbox or datetimes cannot be composed with "OR" when there are several related areas of interest or when trying to query for period-over-period data (e.g., the same month in multiple years)

Thanks!

**Comment by philvarner** [comment]
> Proposal for the CQL2 conformance classes based on the discussion:
> 
> * logical expressions (AND/OR/NOT), sub-expressions and basic comparison predicates on strings/numbers/boolean/instants with properties as first operand, literals as second operand - "BasicCQL"
> * LIKE/BETWEEN/IN operators, UPPER()/LOWER() - "Advanced comparison predicates"
> * spatial predicates
> * temporal predicates
> * array predicates
> * literals also as first operand, properties also as second+ operand - "???"
> * (custom) functions
> * arithmetic expressions

STAC API Filter Extension version 1.0.0-beta.3 is about to be released. We chose to divide up these conformance classes differently, so I'll explain why.  The spec can be found here: https://github.com/radiantearth/stac-api-spec/blob/dev/fragments/filter/README.md#conformance-classes

* Basic CQL is the same.
* Enhanced Comparison Operators with only LIKE, BETWEEN, and IN  (**not** UPPER/LOWER functions). This is because we did not want to require the complexity of implementing function parsing just to get the operators LIKE, BETWEEN, and IN. 
* Basic Spatial Operators (only INTERSECTS)
* Enhanced Spatial Operators (all other spatial operators) -- this is because some databases don't even support some of these operators, so API implementations may only be able to support INTERSECTS (or may only care to)
* Basic Temporal Operators (only ANYINTERACTS)
* Enhanced Temporal Operators (all others) -- same reason as splitting the Spatial operators)

* Functions - same
* Arithmetic - same
* Arrays - same
* Queryable Second Operand -- right now we have this only defined as properties in the second operand, but could change that in beta.4 to also allow literals as the first operand.

I feel strongly that only having one class for spatial and temporal operators is going to make implementations much more difficult and prevent some implmentations from supporting them, and would request that this be reconsidered. I would also like to see UPPER and LOWER split out of the Enhanced Comparison Operators, as it complects the other operators with functions.

**Comment by cportele** [comment]
Enhanced Comparison Operators: While reading your comment, I noticed that I forgot to include UPPER()/LOWER() in the "advanced comparison operators" class. So, currently this is consistent with your approach, but it is more of an oversight on my end. However, I would be open to have those as a separate class.

Queryable Second Operand: I think literal-literal comparisons are really an edge case, because it is equivalent to a true or false constant. I would have no problem to remove this capability in CQL.

Basic Spatial Operators: I know we decided to not do this, but I do not have strong feelings about this. As a set between bbox with a simple envelope and the complete list of pre-defined topological relationships it probably has a place.

Basic Temporal Operators: I do not really see the need for this one, to be honest. First of all, there is already `datetime` that supports this, so the only capability that this adds is that it can be combined with OR or NOT. In addition, implementations that can deal with intervals likely can / will implement all of the operators, which are mostly for intervals. For instants one can use the regular comparison operators. 

Another option could be a Basic Spatial/Temporal Operators class with T_INTERSECTS() and S_INTERSECTS().

**Comment by philvarner** [comment]
wrt Temporal Operators, I think being able to combine intersects with logical operators is an important use case. I also think it's more ergonomical to allow users to write their entire query in CQL and not have to put parts of it in other query parameters like intersects or datetime.

**Comment by cportele** [comment]
I understand, but if the properties that are used are instant (which they usually are), then

`T_INTERSECTS(instant, INTERVAL('1969-07-16', '1969-07-24')`

is equivalent to

`instant >= DATE('1969-07-16') AND instant <= DATE('1969-07-24')`

Is there really enough value to justify a separate conformance class just for T_INTERSECTS()?

**Comment by pvretano** [comment]
@cportele I think there is a case to make made for the basic spatial and temporal operator conformance classes if we consider POSTing a filter expression (or query expression) to a search endpoint.  In that case you can't rely on `bbox` and `datetime` to provide the spatial and temporal filtering.

The case for the basic temporal operators is a little weaker though since you can use comparison operators to do the same thing (as you point out) so maybe a middle ground is splitting the spatial operators into "basic" and the rest and leave the temporal operators as is.  So the conformance classes would be:

- Basic CQL (property-literal comparisons only)
- Enhanced Comparison Operators
- Enhanced Comparisons (i.e. property-literal, property-literal or literal-literal comparisons)
- Basic Spatial Operators
- Enhanced Spatial Operators
- Temporal Operators (all others)
- Functions
- Arithmetic
- Arrays

I would not be in favor of removing `literal-literal` comparisons,  I can see restricting comparisons to `property-literal`; some systems have that restriction already (elastic search I think).  However, if your system can also support `property-property` comparisons it would surely be able to handle 'literal-literal` comparisons.  So why restrict it?  It seems like an odd restriction to me.

**Comment by cportele** [comment]
Fine with me to include literal-literal comparisons and indeed it should not be complicated to support it, if the rest is supported. My point was mainly that it will be rarely used in practice, so it is not a significant difference whether we have requirements for it or not.

OK, so we agree to refactor S_INTERSECTS() to its own requirements class. I will update the PR accordingly.

@philvarner - do you agree that there is not a strong case for having a separate requirements class for T_INTERSECTS()?

And we have the open issue about UPPER()/LOWER() - which I forgot to properly include in my PR so far. There are really two open issues:

* How to properly define UPPER() and LOWER() with all the edge cases outside of the ASCII characters? I do not have access to the SQL standard and could not find information how it defines "uppercase". Or should we define a case folding function instead and how complicated will this be to implement with existing backends? See related discussions from [Unicode](http://unicode.org/reports/tr21/tr21-5.html#Caseless_Matching) and [W3C](https://www.w3.org/TR/charmod-norm/#definitionCaseFolding).
* Should this be in a separate requirements class? Because of the complexity of the topic and since STAC would prefer this, I now think that it should be in its own class.

**Comment by cportele** [comment]
Meeting 2021-08-16: 

* @pvretano will look into how the various backends support upper/lower functions. We will discuss this aspect after the analysis.
* We will also decide, if the support for case-insensitive comparisons should be its own requirements class.
* In the meeting a decision to have S_INTERSECTS() as a req class, but not T_INTERSECTS().

**Comment by philvarner** [comment]
Sorry I didn't get back to you about this before the meeting. 

I have the same concern with having T_INTERSECTS in what is now the Enhanced Temporal Operators as I had for S_INTERSECTS. Some databases like Elasticsearch don't support all of those operators, so then that implementation can't support any conformance class for temporal operators.

**Comment by cportele** [comment]
Thanks @philvarner. But does Elasticsearch support intervals and if the answer is "no", does it really need the temporal operators or are the comparison operators like `>`, `=`, etc. not enough? Temporal is really different from spatial in that respect. What filter expression do you want to support, where you need T_INTERSECTS() and the comparison operators are not sufficient? See https://github.com/opengeospatial/ogcapi-features/issues/579#issuecomment-896233545.

**Comment by philvarner** [comment]
After talking with @pvretano earlier at the STAC API, it seems that one thing I missed was that the basic comparison operators support datetime comparison? 

So if I only implement Comparison operators conformance class, I can write a CQL statement (assuming `datetime` is a queryable) `datetime >= "2014-12-05T12:30:45Z"` and must do the right temporal comparison?

If this is the case, it's not clear in the spec, and the grammar seems to indicate this is not allowed.

**Comment by pvretano** [comment]
@philvarner just checked the BNF to the text encoding  and it allows it.  There seems to be a bug in the JSON encoding which I will fix.  I'll create a PR to fix the JSON encoding problem and clarify the text a bit more too.  Please stand by.

**Comment by pvretano** [comment]
@philvarner OK, I patched the bug in the CQL2 JSON schema to allow standard comparison operators to be used to evaluate simple temporal predicates involving time instants.  The Basic CQL2 clause already includes a permission for this.  I added a reciprocal note to the "Temporal Operators" clause pointing back to the relevant sections in the Basic CQL2 clause.  I hope that is sufficient clarity.  Let me know if it is not ...

**Comment by cportele** [comment]
Reopened, because the approach to case-insensitive comparisons is still open (https://github.com/opengeospatial/ogcapi-features/issues/579#issuecomment-899550990):

* @pvretano will look into how the various backends support upper/lower functions. We will discuss this aspect after the analysis.
* We will also decide, if the support for case-insensitive comparisons should be its own requirements class.

**Comment by pvretano** [comment]
@cportele oops!  Didn't mean to close this.  Thanks for reopening.

**Comment by philvarner** [comment]
I can't remember if I commented on lower/upper or not, but I would prefer this be a separate conformance class because including it in the IN/BETWEEN/LIKE class would require implementers to implement function parsing (even if just for these two named function) just to advertise IN/BETWEEN/LIKE support. This makes it a much bigger piece of work and I worry could harm adoption.

**Comment by philvarner** [comment]
> @philvarner just checked the BNF and the text encoding allows using standard comparison operators to evaluate simple temporal predicates involving time instants. There seems to be a bug in the JSON encoding, though, which I will fix. I'll create a PR to fix the JSON encoding problem and add more text to clarify this use case. Please stand by.

Ah, I see this wasn't present in the draft for CQL Text, but was added last month https://github.com/opengeospatial/ogcapi-features/commit/7c3e18c7b93bf166f9a8b448e653328df898fc18

I should probably go through the latest version again and start using that as a reference. 

Thanks!

**Comment by philvarner** [comment]
I just created a PR to realign STAC API - Filter Extension with this https://github.com/radiantearth/stac-api-spec/pull/202/files

The classes are now aligned with the exception that we do not require upper/lower as part of Advanced Comparison Ops.

Though, I am reconsidering that. Now that `IS NULL` is part of the Basic CQL, `LIKE` is the only operator that can't otherwise be expressed in Basic CQL  (e.g., IN and BETWEEN can be converted to more verbose clauses).  

I would prefer that an implementor didn't need to implement function parsing to support this class, but I think, ultimately, it's not worth having this minor difference between STAC API and OAFeat CQL2, so I'll defer to whatever y'all finalize.

**Comment by cportele** [comment]
Meeting 2021-08-30: We will separate the case-insensitive comparison support into a separate requirements class. This satisfies the preference from the STAC community and also helps to separate this capability where we had lots of discussions into a separate module. What is still open is the details on how we provide the capability (still a @pvretano action). @cportele will introduce the new requirements class in the document.

**Comment by philvarner** [comment]
Thanks!
