### ISSUE TITLE
CQL2 JSON encoding

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#601]
# CQL2 JSON encoding options

There are two proposals for the CQL2 JSON encoding. They are currently described [here](https://docs.ogc.org/DRAFTS/19-079r1.html#cql2-json) and [here](https://github.com/tschaub/ogcapi-features/tree/json-array-expression/extensions/cql/jfe). 

The first option is the current text in the draft standard and uses JSON objects for predicates and JSON arrays for operands.

The second option was developed during one of the OGC Code Sprints and uses JSON arrays only (except for the GeoJSON geometries). It is inspired by the expressions in the [Mapbox Style specification](https://docs.mapbox.com/mapbox-gl-js/style-spec/). One effect of this is differences in how operators are named (e.g., "==" instead of "=", "all" instead of "and", "get" instead of "property").

The Standards Working Group (SWG) wants to adopt only one JSON encoding for CQL2 and is looking for feedback which one should be adopted. This comment provides a side-by-side comparison of four examples to get a quick overview. The complete set of examples is available [here](https://github.com/opengeospatial/ogcapi-features/tree/master/extensions/cql/standard/schema/examples).

The SWG currently does not have good reasons for picking one option over the other. Both options seem similar with the differences listed above (use of objects vs arrays, differences in the names). We are interested in feedback, if there are preferences in terms of the style or good reasons for preferring one option, because it is easier to process or create.

If you prefer the **first option**, please add a "thumbs up" in [this comment](https://github.com/opengeospatial/ogcapi-features/issues/601#issuecomment-917951951).

If you prefer the **second option**, please add a "thumbs up" in [this comment](https://github.com/opengeospatial/ogcapi-features/issues/601#issuecomment-917952145).

Comments on specific advantages or disadvantages of the options are very welcome, too.

## Example 1

```text
scene_id = 'LC82030282019133LGN00'
```

<table>
<tr>
<th width='50%'> Option 1 </th>
<th width='50%'> Option 2 </th>
</tr>
<tr>
<td>

```json
{
   "=": [
      {
         "property": "scene_id"
      },
      "LC82030282019133LGN00"
   ]
}
```

</td>
<td>

```json
[
   "==",
   [
      "get",
      "scene_id"
   ],
   "LC82030282019133LGN00"
]
```

</td>
</tr>
</table>

## Example 2

```text
eo:cloud_cover BETWEEN 0.1 AND 0.2
   AND landsat:wrs_row=28
   AND landsat:wrs_path=203
```

<table>
<tr>
<th width='50%'> Option 1 </th>
<th width='50%'> Option 2 </th>
</tr>
<tr>
<td>

```json
{
   "and": [
      {
         "between": [
            {
               "property": "eo:cloud_cover"
            },
            0.1,
            0.2
         ]
      },
      {
         "=": [
            {
               "property": "landsat:wrs_row"
            },
            28
         ]
      },
      {
         "=": [
            {
               "property": "landsat:wrs_path"
            },
            203
         ]
      }
   ]
}
```

</td>
<td>

```json
[
   "all",
   [
      "between",
      [
         "get",
         "eo:cloud_cover"
      ],
      0.1,
      0.2
   ],
   [
      "==",
      [
         "get",
         "landsat:wrs_row"
      ],
      28
   ],
   [
      "==",
      [
         "get",
         "landsat:wrs_path"
      ],
      203
   ]
]
```

</td>
</tr>
</table>

## Example 3

```text
eo:instrument LIKE 'OLI%' AND S_INTERSECTS(footprint, POLYGON((43.5845 -79.5442, 43.6079 -79.4893, 43.5677 -79.4632, 43.6129 -79.3925, 43.6223 -79.3238, 43.6576 -79.3163, 43.7945 -79.1178, 43.8144 -79.1542, 43.8555 -79.1714, 43.7509 -79.6390, 43.5845 -79.5442)))
```

<table>
<tr>
<th width='50%'> Option 1 </th>
<th width='50%'> Option 2 </th>
</tr>
<tr>
<td>

```json
{
   "and": [
      {
         "like": [
            {
               "property": "eo:instrument"
            },
            "OLI%"
         ]
      },
      {
         "s_intersects": [
            {
               "property": "footprint"
            },
            {
               "type": "Polygon",
               "coordinates": [
                  [
                     [43.5845,-79.5442],
                     [43.6079,-79.4893],
                     [43.5677,-79.4632],
                     [43.6129,-79.3925],
                     [43.6223,-79.3238],
                     [43.6576,-79.3163],
                     [43.7945,-79.1178],
                     [43.8144,-79.1542],
                     [43.8555,-79.1714],
                     [43.7509,-79.6390],
                     [43.5845,-79.5442]
                 ]
              ]
            }
         ]
      }
   ]
}
```

</td>
<td>

```json
[
   "all",
   [
      "like",
      [
         "get",
         "eo:instrument"
      ],
      "OLI%"
   ],
   [
      "s_intersects",
      [
         "get",
         "footprint"
      ],
      {
         "type": "Polygon",
         "coordinates": [
            [
              [43.5845,-79.5442],
              [43.6079,-79.4893],
              [43.5677,-79.4632],
              [43.6129,-79.3925],
              [43.6223,-79.3238],
              [43.6576,-79.3163],
              [43.7945,-79.1178],
              [43.8144,-79.1542],
              [43.8555,-79.1714],
              [43.7509,-79.6390],
              [43.5845,-79.5442]
          ]
        ]
      }
   ]
]
```

</td>
</tr>
</table>

## Example 4

```text
T_AFTER(built, DATE("2012-06-05"))
```

<table>
<tr>
<th width='50%'> Option 1 </th>
<th width='50%'> Option 2 </th>
</tr>
<tr>
<td>

```json
{
   "t_after": [
      {
         "property": "built"
      },
      {
         "date": "2012-06-05"
      }
   ]
}
```

</td>
<td>

```json
[
   "t_after",
   [
      "get",
      "built"
   ],
   [
      "date",
      "2012-06-05"
   ]
]
```

</td>
</tr>
</table>

**Comment by pvretano** [comment]
Current CQL examples re-encoded using @tschaub proposed JSON encoding created [here](https://github.com/opengeospatial/ogcapi-features/tree/master/extensions/cql/standard/schema/examples/alt-json-encoding).  Hopefully I encoded them correctly! ;)

**Comment by cportele** [comment]
Meeting 2021-08-30: How do we get enough feedback / opinions which JSON encoding is easier to parse / generate / validate? @cportele will create a side-by-side comparison on key examples in this issue and then we can ask for comments / votes with thumbs-ups for each of the two options. Promote this at the member meeting and review the results in the meeting in 4 weeks.

**Comment by cportele** [comment]
There are two proposals for the CQL2 JSON encoding. See [the first comment in this issue](https://github.com/opengeospatial/ogcapi-features/issues/601#issue-937169104).

If you prefer the first option please add a "thumbs up" to this comment.

**Comment by cportele** [comment]
There are two proposals for the CQL2 JSON encoding. See [the first comment in this issue](https://github.com/opengeospatial/ogcapi-features/issues/601#issue-937169104).

If you prefer the **second option** please add a "thumbs up" to this comment.

**Comment by m-mohr** [comment]
IMHO this issue doesn't give enough context.
- Are there any known (dis)advantages that the options have?
- I'm especially wondering what the excessive use of "get" is useful for in Option 2?
- Why is it "=" in one of the examples and "==" in others?
- Is there any advantage aligning with the Mapbox Style specification? To me option 1 seems easier overall.

PS: Example 1 - Option 2 seems broken.

**Comment by cportele** [comment]
@m-mohr - Thanks for the feedback. 

I have added an explanation to address your items 2 and 3 (this is to align with the Mapbox Style expressions which uses different tokens/names). The advantage for aligning with Mapbox Style could be the reuse of existing code for parsing or generating such expressions or the fact that these expressions use a familiar style. But of course, this applies only to those that have been or are working with those styles.

As for other (dis)advantages of the options, we do not really have a clear view, which is one of the reasons for this issue and the request to look for broader feedback. I have implemented option 1, but parsing/processing option 2 expressions should work more or less the same way. I have also added a bit of text about this.

I have also fixed the property name in example 1 - option 2.

**Comment by jerstlouis** [comment]
Big preference for Option 1 on my side.
My understanding is that the whole point of having a JSON encoding for CQL2 (I would otherwise argue one is not needed) is that it does not require any special parsing and is an as-direct-as-possible object encoding of the CQL2 Abstract Syntax Tree.

Converters between MapboxGL style expressions can be written for those who would like this convenience.

In general I find the MapboxGL styles syntax extremely counter-intuitive, and the left-side/right-side expression rules (e.g. what is allowed on which side, and when is GET required or not) for different versions make things even more complicated.

**Comment by philvarner** [comment]
One thing I notice is that the difference between 1 & 2 conflate two different design decisions. Option 1 reuses the keywords (e.g., "and" is conjunction) from CQL Text and puts them in a JSON structure that feels pretty standard to me, whereas Option 2 changes the keywords (e.g., conjunction is "all" instead) and provides a JSON structure that is more LISP-like than I think is typical for "mainstream" use. 

I'm strongly in favor of Option 1 between these two options, but I would be more amenable to Option 2 if it used the same keywords as CQL Text instead of the MapboxGL terms.

**Comment by jisantuc** [comment]
Parsing mapbox style expressions into data is really rough -- especially with the nesting rules (e.g. you can't `["get", ["get", "lookupKey"]]`). Even with TypeScript support, correct non-trivial mapbox style expressions are (for me at least) pretty hard to author. It's _way easier_ to imagine a schema for Option 1. Moreover, I think heterogeneous lists where the structure is encoded in array indices are a design smell -- there's obviously structure / semantics, but e.g. "an array where the first element is a string and the second is a double" rarely expresses the structure / semantics at all.

**Comment by tschaub** [comment]
I'm not really trying to lobby for Option 2 over Option 1 – I can tell that Option 2 is not popular with this crowd.  But, I will drop a few comments anyway.

I assume that anyone who regularly works with JSON would see an object like `{"or": ...}` and wonder what it is supposed to mean of the object has more than one member like `{"or": ..., "and": ...}`.

Since JSON objects are **unordered** collections of one or more name/value members, there is no "first" member name.  While the first object above might make for a nice (human-)readable "OR expression," the second object is ambiguous (OR?, AND?, maybe an implicit OR with a child OR and AND?).

I know that a validator can detect that the second form is invalid, but to me, using an object to represent a single name/value pair is JSON-smell.  And if I see code that switches on the "first" member name in an object (to determine the expression type), that would strike me as code smell.

Disparaging remarks aside, I do see how `{"or": ...}` in JSON is tantalizingly similar to `<Or ...>` in XML.  So I can understand how it seems like a nice incremental upgrade.  And even if people don't have any exposure to OGC Filter Encoding, I also get how the LISP-like syntax of Option 2 is off-putting.  All I can say is that after having used it for style expressions in other projects for a while, it has grown to be a syntax that feels nice to me – but I have no idea if others would find the same.

It is probably fair to say that the "type-safeness" of the two data forms is equally mediocre.  But having written [a parser for the second form](https://github.com/tschaub/jiffy) in a type safe language, I can say that it wasn't hard.

**Comment by jerstlouis** [comment]
@tschaub I share some of your concerns for Option 1, and I was originally wondering where Option 3 was :)
I believe the intent is that there is always a single key inside those Option 1 objects.
So in effect they key is the operator, and the value is the operands.

Personally, I would have preferred something that is even closer to the AST, e.g.:

```json
{
   "operator": "and",
   "operands" : [
      {
         "operator" : "between",
         "operands" : [
            {
               "property": "eo:cloud_cover"
            },
            0.1,
            0.2
         ]
      },
      {
         "operator" : "=",
         "operands": [
            {
               "property": "landsat:wrs_row"
            },
            28
         ]
      },
      {
         "operator" : "=",
         "operands" : [
            {
               "property": "landsat:wrs_path"
            },
            203
         ]
      }
   ]
```
It could have used "op" instead of "operators", and "values" instead of "operands" as well for a more concise syntax.

**Comment by tschaub** [comment]
@jerstlouis - I agree that if you want to use JSON objects to represent an expression, it makes sense to have `operator` or `type` as a member to switch on.  Though I would choose a different style for the accessor expression (your `{"property": ...}`) – an `operator` (or `type`) value of `get` makes sense to me there.

Then if you wanted something a bit less verbose, maybe you can imagine using positions in an array instead of named members in an object.  So instead of `expr.operator` you would have `expr[0]` and instead of `expr.operands` you would have `expr[1:]` (or `expr.slice(1)`).  And then you are at Option 2 😃

**Comment by jerstlouis** [comment]
> Though I would choose a different style for the accessor expression (your {"property": ...}) – an operator (or type) value of get makes sense to me there.

I don't really see properties as an [operation expression](https://github.com/ecere/ecere-sdk/blob/329791ae81deca4b5e5f582b591fb40d8eb65662/compiler/eccss/expressions.ec#L663), they're more like [identifier expressions](https://github.com/ecere/ecere-sdk/blob/329791ae81deca4b5e5f582b591fb40d8eb65662/compiler/eccss/expressions.ec#L566).

> maybe you can imagine using positions in an array instead of named members in an object. So instead of expr.operator you would have expr[0] and instead of expr.operands you would have expr[1:] (or expr.slice(1)).

That is the part I strongly dislike :) It was extremely difficult to parse and then work with that data model in our MapboxGL parser, where elements of the array are all sort of different things:

```eC
   Array<MBGLFilterValue> params = filter.type.type == blob ? (Array<MBGLFilterValue>)filter.b : null;
   String op = params && params.count && params[0].type.type == text ? params[0].s : null;
   if(op && params.count >= 2)
   {
      if(!strcmpi(op, "get"))
      {
```

**Comment by cportele** [comment]
Meeting 2021-09-27: From the two options there is a preference for the first option. However, there is value in considering the issues raised in the last comments and come back to this issue at the next meeting in two weeks and after we got more input from others that might use CQL2 in the future. 

@philvarner - Any view from the STAC perspective on @jerstlouis proposal in https://github.com/opengeospatial/ogcapi-features/issues/601#issuecomment-921331198, which is a variation of option 1 that is more verbose, but closer to the abstract syntax tree?

In any case we need to ensure that in option 1 `{ "and": [ ... ] , "or" : [ ... ] }` is not valid (add `additionalProperties: false` and add text in the document).

**Comment by philvarner** [comment]
I don't have a strong opinion between them, and I think there's clear difference wrt STAC. Personally, I dislike when the "value" is used as an attribute name (as in option 1) and prefer when the value is an attribute value (as in jerstlouis's proposal). It's more verbose, but also has a more consistent structure.

**Comment by m-mohr** [comment]
Yes, I agree that @jerstlouis proposal seems best to me, too. That's most verbose, but can be created and transformed most easily, IMHO. Which would also be nice for openEO use cases.
