### ISSUE TITLE
How to get the collection schema?

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#612]
[Recommendation 2](https://docs.ogc.org/DRAFTS/20-002.html#feature-representations) of Part 4 specifies that the schema that should be retrieved from the `/collections/{collectionId}/schema` endpoint is the schema of a **feature**.  The example and requirements that follow [Recommendation 2](https://docs.ogc.org/DRAFTS/20-002.html#feature-representations) use a parameter named `type` to retrieve the `create`, `replace` or `update` schema of a feature.

My question is: How would someone get the schema of the collection so that it could be used to validate the response from `/collections/{collectionId}/items` endpoint?

In my implementation I have added the enumeration value `collection` for the `type` parameter so that `/collections/{collectionId}/schema?type=collection` returns the schema of the feature collection rather than of a feature. 
 However, this is just my implementation.  I created this issue so that we can discuss a mechanism for retrieving the collection schema.

**Comment by cportele** [comment]
Here is how we have addressed this for now in ldproxy:

Create separate endpoints for the feature schema (`/collections/{collectionId}/schemas/feature`) and feature collection schema (`/collections/{collectionId}/schemas/collection`), because these are arguably different resources. That said, maybe it should be `.../item` rather than `.../feature`?

In the meeting on 2021-08-02 we decided to park the issue until we get to it in the discussion of part 4 or the new schema part.

**Comment by cportele** [comment]
I think we can close this issue, it is no longer relevant. There was a decision that the schemas are an encoding-agnostic representation of the logical data schema.

Schemas for validation can still be linked to responses. A feature will link to the schema of a feature, a feature collection will link to the schema of the feature collection. These schemas can be hosted anywhere.

**Comment by cportele** [comment]
Meeting 2023-06-19: This can be closed, it is no longer relevant as explained in the previous comment.
