### ISSUE TITLE
Part4: PUT/PATCH without eTag 

### ISSUE THREAD

**Issue by benoitdm-oslandia** [opengeospatial/ogcapi-features#735]
Hi,

I looked through the spec and could not find expected server behavior when the incoming PUT/PATCH request is missing the eTag.

Should it fail with a specific error code or ...?

**Comment by cportele** [comment]
If the server does not support the "Optimistic Locking" conformance class, the assumption is that the server will ignore the `If-Match` request, since it does not advertize support for conditional requests.

If the server supports the "Optimistic Locking" conformance class and the client sends a request without an `If-Match` header, the server will respond with an error. See `/req/optimistic-locking/ifmatch-put-op` and `/req/optimistic-locking/ifmatch-patch-op`. 

There is currently no discussion about the status code, probably we should add something. 412 is not applicable in this case, because the client has not specified any pre-conditions that could fail. I see two options for the server: either 409 (Conflict), if the server wants to restrict itself to status codes from the HTTP standard, alternatively it could return [428 (Precondition Required)](https://www.rfc-editor.org/rfc/rfc6585#section-3) from RFC 6585.

**Comment by benoitdm-oslandia** [comment]
Thanks @cportele!

**Comment by cportele** [comment]
I reopen the issue as I think we should discuss what we write in the document regarding the server behavior, if the conformance class "Optimistic Locking" is supported, but no "If-Match" header is sent.

My proposal would be that we explicitly state that the behavior depends on the API (that is, the server may replace/update/delete the resource or it may decide to reject the request with a 428 or 409 status code). I do not think that we can or should enforce a behavior as the server policy may depend the data and use case.

**Comment by cportele** [comment]
Meeting 2022-09-12: @pvretano will address this together with the related PRs on optimistic locking.

**Comment by cportele** [comment]
Meeting 2022-10-24: @cportele will include this in #774.
