### ISSUE TITLE
Part 4: server supported functionnalities

### ISSUE THREAD

**Issue by benoitdm-oslandia** [opengeospatial/ogcapi-features#736]
From the spec, it is mentioned on http://docs.ogc.org/DRAFTS/20-002.html#feature-representations this condition "The server has schema constraints for features in a collection". 

Does it means the server could have no schema constraint? 

If this is the case, what should be the server HTTP response code? And, also, is there somewhere we have to describe the server capabilities (like the WMS GetCapabilites)?

**Comment by cportele** [comment]
Meeting 2022-09-12: 

> Does it means the server could have no schema constraint?

We want to support servers that are "schema-less" (e.g., with a document data store are the backend), but many servers will have underlying schema constraints. Those servers should publish the schemas in order to help clients to create requests that are not rejected.

> If this is the case, what should be the server HTTP response code? 

If there is no schema constraint and the submitted resource meets the requirements of the media type (e.g., a valid GeoJSON feature), the resource will be created/updated with a 20x status.

> And, also, is there somewhere we have to describe the server capabilities (like the WMS GetCapabilites)?

The server has to publish its API definition, its Conformance Declaration and may publish the schemas, for example. Here is a link to the current proposal for publishing the schemas: https://github.com/opengeospatial/ogcapi-features/tree/master/proposals/schemas

**Comment by cportele** [comment]
Meeting 2022-10-24: We should add an informative description about schemas (or the lack of them) in the document. @pvretano will work on a PR.

**Comment by cportele** [comment]
Closed by #823
