### ISSUE TITLE
Part 1: Clarify `datetime` parameter (wording clearly targeting server) and related issues

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#772]
Currently [Requirement 26 D (of the editor's draft):](https://docs.ogc.org/DRAFTS/17-069r5.html#_parameter_datetime) says:

> _Temporal geometries **are either** a date-time value **or** a time interval. The **parameter value SHALL** conform to the following syntax (using [ABNF](https://www.rfc-editor.org/rfc/rfc2234.html)): [...]_

The wording does not reflect the target of the standard (the Web APIs, not the parameters provided by the client), and as a result it may not be obvious to all implementers that services SHALL support BOTH time instants (date-time values) and time intervals.

Reporting this while investigating an actual implementation that does not support both (although that is likely an implementation bug rather than an omission).

The corresponding Abstract Test 22 does not seem to be described in a way that would unambiguously result in an ETS testing this properly:

> _Test Purpose: Validate that the datetime query parameters are constructed correctly.
Test Method: Verify that the datetime query parameter complies with the following definition (using an OpenAPI Specification 3.0 fragment [...]._

There are at least two other Abstract Tests with similar problems, which may also reflect issues in the corresponding requirements:

> Abstract Test 18 (_fc-bbox-definition_): _Validate that the bounding box query parameters are constructed correctly._

> Abstract Test 20 (_fc-limit-definition_): _Validate that the **bounding box** query parameters are constructed correctly._

(AT 20's purpose should actually be talking about the **limit**, not the bounding box)

**Comment by cportele** [comment]
The requirement is for the server (the grammar that the server has to accept) not for the client (which can send any value that conforms to the grammar). Maybe we reword this slightly so that this is clearer.

The wording in the test(s) indeed needs to be improved. Mainly the test method, but the work "constructed" in the test purpose is misleading, too. 

I assigned this to me to work on a PR.

Regarding the ATS, it probably would be good to change the test methods to the given-when-then style we use in Part 3 and CQL2, but this would be something for a future version 1.1.
