### ISSUE TITLE
cql2.bnf is it valid BNF?

### ISSUE THREAD

**Issue by tfiner** [opengeospatial/ogcapi-features#854]
I can't find for the life of me, a BNF spec where '#' is a comment character.  No tools I've tried to use against it work, all of them start by complaining about the '#' marks.  ABNF uses ';'  LBNF uses '--'  `{- ... -}`, EBNF uses `(* ... *)`.

It would be really helpful to me, if the variant of BNF that this file is in had a link to the spec. it is using.  Even better, what tooling are you using to generate parsers with?

Also, the validation tool mentioned in the bnf (https://www.icosaedro.it/bnf_chk/bnf_chk-on-line.html) says that the file is invalid as well.

**Comment by eseglem** [comment]
The problem with EBNF is there is not really a single format that everyone uses.

ISO says `(* ... *)` [1] but W3C uses `/* ... */` [2] and this article [3] mentions a paper which counted at least 42 different ways it was being defined. With the reliance on the XML spec for a lot of pieces, it might be good to switch over to that format? But I do not see a real issue with the way it is either. The grammar defined in the file is understandable as it is, and I do not know if basing things on a specific tool being able to read it is necessary? 

Interestingly the `bnf_chk` tool does not even define comments so neither format works. It seems to just ignore the lines that start with `#`. The only issue it has with the current file in the repo is with `escapeQuote = "''" | "\'";` This is because of how they define strings. It tries to read `\'` as an escape sequence and not a literal string. Which feels very weird to me. It wants to escape the slash first: `\\'`. 

The closest grammar I have found to this one is actually Python [4] which is a mixture of EBNF and PEG. It uses `:` vs `=` and has lookaheads, but also `#` comments. 

Personally, I didn't use any tools to generate a parser directly from what is included here. Due to the lack of standards and tooling. I just wrote a Lark parser by hand based on the grammar [5]. It is also a EBNF like grammar, so it was not too bad. Started with replacing `=` with `:` and making it snake case, and went from there. Though I am currently working on updating it to match the latest version again, as it is still evolving. 

[1] https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form 
[2] https://www.w3.org/TR/REC-xml/#sec-notation
[3] https://dwheeler.com/essays/dont-use-iso-14977-ebnf.html
[4] https://docs.python.org/3/reference/grammar.html
[5] https://github.com/eseglem/pycql2/blob/main/pycql2/cql2.lark

**Comment by tfiner** [comment]
@eseglem Thanks for all that info and appreciate .  I'm just looking to avoid writing yet another parser, heh.  I'll probably just select a parser generator that complains the least with the given BNF and go from there.  i didn't know about Lark, so I'll probably use your cql2.lark too, thanks again!

**Comment by cportele** [comment]
Code Sprint 2024-02-26: Since there are many variations of EBNF, we should focus on verifying that the grammar validates with the validator that we reference. If other tools use a different variant, the grammar needs to be adapted in the implementation context. This is true for most implementation, e.g., including ANTLR. We can add a disclaimer that makes this explicit. @pvretano will create a PR.
