### ISSUE TITLE
Replace mentions of "OGC APIs"

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-features#880]
There is a request from the OAB for clearer use of terminology regarding OGC API Standards. 

The detail of the Issue is documented at https://github.com/opengeospatial/ogcapi-common/issues/336

This ogcapi-features Issue may be closed once the relevant edits have been made to OGC API - Features Standards documents.

**Comment by cportele** [comment]
I am closing this, because OGC API Features does not use "OGC APIs". 

There is one use in the Security Considerations section of part 1, but this will be changed as part of a [pull request](https://github.com/opengeospatial/ogcapi-features/pull/878) that includes other editorial changes as a result of the ISO DIS ballot.
