### ISSUE TITLE
CQL2: Validation of JSON examples fails

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/ogcapi-features#901]
I am facing issues with validating the [CQL2 JSON examples](https://github.com/opengeospatial/ogcapi-features/tree/master/cql2/standard/schema/examples/json) in this repository using the provided schema file [cql2.json](https://github.com/opengeospatial/ogcapi-features/blob/master/cql2/standard/schema/cql2.json). I have tried the following tools for validation:

1. An online [JSON Schema Validator](https://www.jsonschemavalidator.net/)
2. The [Ajv command-line tool](https://github.com/ajv-validator/ajv-cli)
3. The [json-schema-validator](https://github.com/networknt/json-schema-validator) Java library

All the examples I have tested do not pass validation in any of the tools. Even simple examples like [example01.json](https://github.com/opengeospatial/ogcapi-features/blob/master/cql2/standard/schema/examples/json/example01.json) fail:

```json
{
  "op": "=",
  "args": [
    { "property": "landsat:scene_id" },
    "LC82030282019133LGN00"
  ]
}
```

It seems that each argument in the `"args"` array matches multiple sub-schemas in cql2.json and not just one. So, replacing all `"oneOf"` rules in  cql2.json with `"anyOf"` solved the problem for me and I could successfully validate the examples with each tool. Note, that I have not done the exercise for all example files.

What tools are you using for validating CQL2 expressions in JSON? Can you give me a hint as to what I am doing wrong?

**Comment by cportele** [comment]
Thank you for spotting this. It has been a while since I validated the JSON examples, but I also encounter the problems. We need to fix the cql2.json schema.

I also notice that version 2019-09 is declared, but `prefixItems` is used, but it was added in 2020-12, I think. In any case, I think we should use 2020-12.

If there is no objection raised in the SWG vote, I would propose to upload the candidate to Pending today, address this issue as well as #800 before the Delft meeting and upload an updated version of CQL2 to Pending.

**Comment by pvretano** [comment]
@cportele I made the changes that @clausnagel suggested and validated all the JSON examples with the [JSON Schema Validator](https://www.jsonschemavalidator.net/) tool.  The only issues is that the [JSON Schema Validator](https://www.jsonschemavalidator.net/) tool is only good up to Draft 2019-09.  In any case, I've started a PR to fix the issue.  I'm going to try the other tools @clausnagel tried just to make sure and also see if draft 2019-09 is supported by any of them.

In the mean time, however, I agree, lets upload to pending and we can revise once I've worked through the PR.

**Comment by cportele** [comment]
@pvretano - I used [ajv](https://www.npmjs.com/package/ajv-cli), which is also used [in JSON-FG](https://github.com/opengeospatial/ogc-feat-geo-json/blob/main/core/examples/validate.sh). 

When I switch on strict validation it reports `prefixItems` as an unknown keyword. If I change to 2020-12, it reports `additionalItems` as an unknown keyword. So we have a mix of versions at the moment. 

In general, in 2024 we should use the 2020-12 version, which is over 3 years old and now supported by most tools that are maintained. It is also the version used in OpenAPI 3.1. This is also what we do in JSON-FG. 

In general, replacing "oneOf" with "anyOf" does not sound like the correct fix to me. If an instance matches multiple options, this should indicate a problem, because it implies that an expression can be interpreted in multiple ways. I will have a look at the sources for these issues.

**Comment by pvretano** [comment]
@cportele that is why I have not posted the PR yet ... I'm trying to figure out where the duplicate schema is that is causing the "oneOf" to fail.  Let me if you come up with something ...

**Comment by clausnagel** [comment]
Thanks @cportele and @pvretano for quickly working on this. As I am not a JSON expert, I also feel like simply replacing "oneOf" with "anyOf" is not a proper fix. Was just some quick hack for my tests. So, glad to see that you investigate this in more depth. I am happy to support you with additional tests using the Java library mentioned once a PR is available.

**Comment by cportele** [comment]
@pvretano - I think, I have found the issue. The problem is that some definitions are valid in various "oneOf" branches. This applies in particular to "propertyRef" and "functionRef". 

Take example01.json as an example:

```json
{
  "op": "=",
  "args": [
    { "property": "landsat:scene_id" },
    "LC82030282019133LGN00"
  ]
}
```

`{ "property": "landsat:scene_id" }` matches "characterExpression", "numericExpression" and "temporalInstantExpression", because "propertyRef" is included in all of them, so "oneOf" fails. If I remove "numericExpression" and "temporalInstantExpression" from the "oneOf" in "scalarExpression", the example is reported as valid.

I will have a look, if I can come up with an approach that avoids this issue.
