### ISSUE TITLE
type casts and NULL about IsInListPredicate

### ISSUE THREAD

**Issue by kunlinyu** [opengeospatial/ogcapi-features#971]
I am develping a c++ parser and evaluator for CQL2. https://github.com/IndoorSpatial/cql2cpp
When I handling the IsInListPredicate, I go through the document and have two questions:

According to Requirement 7.B
https://github.com/opengeospatial/ogcapi-features/blob/master/cql2/standard/requirements/advanced-comparison-operators/REQ_in-predicate.adoc

My understanding is, all queries below are invalid
```text
speed IN ('black', 'happy', TRUE)
3 IN ('color', FALSE)
3+2 IN ('x', 'y')
```

But according to Permission 2.A
https://github.com/opengeospatial/ogcapi-features/blob/master/cql2/standard/recommendations/basic-cql2/PER_type-casts.adoc
"the server MAY either return an error or it MAY cast the operands to compatible data types"

I Want to confirm that:
***Question 1***: Can I (and should I) do some type cast in my libray to handle this and return TRUE?
```text
3.2 IN (3.2)    // TRUE
3.2 IN ('3.2')    // TRUE
3.2 IN ('+3.2')    // TRUE
```

***Question 2***: What should I do if the value of left part is NULL?
for example
```text
name IN ('Alice', 'Bob')  // the "name" is not a queryable in the data source.
unknow_func('A', TRUE) IN ('Alice', 'Bob', unknow_func('B', FALSE))  // Null IN ('Alice', 'Bob', Null)
```

**Comment by cportele** [comment]
Yes, the three `IN` expressions are all invalid as their semantics is undefined, but the permission allows that implementations can cast values so that all values are compatible with each other.

Whether your implementation rejects the last two expressions in **Question 1** or not and the strings are cast to a number or the number is cast to a string is your decision.

With respect to `NULL` (**Question 2**) the usual rules apply. If the left-hand side is `NULL`, the `IN` predicate evaluates to `NULL`. 

By the way, if "name" is not a queryable the result could also be an error as "name" is not a valid property reference.

**Comment by kunlinyu** [comment]
@cportele Thank you! I will consider about it.
